#!/bin/sh

MIXER=`sed 's/,.*//' /tmp/mixer_control_cache`

start() {
    touch /var/log/aplayer.log
    ln -s -f /var/log/aplayer.log /usr/aprenderer/aplayer.log
    printf "Starting APlayer: "
    cd /usr/aplayer; nice -n -30 ./aplayer > /dev/null 2>&1 && echo "OK" || echo "FAIL"
    sync
    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" unmute 2>/dev/null
    }
stop() {
    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" mute 2>/dev/null
    killall -9 aplayer
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
