#!/bin/sh

MIXER=`sed 's/,.*//' /tmp/mixer_control_cache`

start() {
    touch /var/log/aprenderer.log
    ln -s -f /var/log/aprenderer.log /usr/aprenderer/aprenderer.log
    printf "Starting APlayer UPNP: "
    cd /usr/aprenderer; ./ap2renderer > /dev/null 2>&1 && echo "OK" || echo "FAIL"
    sleep 0.5
    pid=$(pidof ap2renderer)
    if [ -n "$pid" ]; then
    renice -15 $pid
    for tid in $(ls /proc/$pid/task/); do
        renice -15 $tid
    done
    fi
    sync
    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" unmute 2>/dev/null
    }
stop() {
    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" mute 2>/dev/null
    killall -9 ap2renderer
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
