#!/bin/sh

MIXER=`sed 's/,.*//' /tmp/mixer_control_cache`

start() {
    printf "Starting NAA: "
    /usr/sbin/networkaudiod > /dev/null 2>&1 &
    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" unmute 2>/dev/null
    }
stop() {
    [ -n "$MIXER" ] && /usr/bin/amixer set "$MIXER" mute 2>/dev/null
    killall -9 networkaudiod
}
restart() {
	stop
	start
}
case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
